### ISSUE TITLE
DefaultEventConsumerImpl consumes Exception and returns success

### ISSUE THREAD

**Issue by regunathb** [Flipkart/aesop#15]
The DefaultEventConsumerImpl consumes an OperationNotSupportedException, simply logs it and finally returns ConsumerCallbackResult.SUCCESS.
Isn't this masking an error that should ideally cause the ConsumerCallbackResult to fail instead?

**Comment by aryaKetan** [comment]
This is the case, where-in consumers have not mapped say an UPSERT or a
DELETE Event. In that case, we dont want consumers to get stuck . I guess
thats why its get logged and returns a success.

Arya

**Comment by jagadeesh-huliyar** [comment]
No. This is the case where a DestinationStoreOperation configured to handle
the event says that i am not capable of handling the event.
This is a bug. In case the user does not want to handle an event, a NO-OP
handler can be configured.

Thanks and Regards
Jagadeesh

**Comment by regunathb** [comment]
DefaultEventConsumerImpl#processSourceEvent() now returns a ConsumerCallbackResult.ERROR when it encounters an unsupported operation. Like Jagadeesh suggested, users may configure a no-op handler if they dont want to process an event.
