### ISSUE TITLE
Adding new Avro schema from mysql-Elasticsearch

### ISSUE THREAD

**Issue by karims** [Flipkart/aesop#36]
I have created a new Avro schema for a particular new Database and Table I had created. My goal is to transfer changes from mysql to Elasticsearch for this new table I created.

I have put the schema in MySql relay distribution/schemas_registry. Mysql relay works fine. But, in the spring-client-config.xml of ES, it is not picking up the new schema. 

I get this error: 
```
14:03:49.057 [pz_elastic_search_cluster-1-RelayDispatcher] ERROR c.l.databus.client.GenericDispatcher.doCheckStartSource 527 es_test_bookings_pz_elastic_search_cluster-1 - Unable to find schema: srcid=2001 name=com.flipkart.aesop.events.es_test.bookings schemaId=055f1eedd345aa57fd55e44583260210
```

My schema is: com.flipkart.aesop.events.es_test.bookings
Can you help me in this? Do ask me if you want more questions.

**Comment by pratyay-banerjee** [comment]
Can you share the spring-clientt-config.xml and the spring-relay-config.xml, as this appears to be a config issue.

**Comment by karims** [comment]
sprint-relay-config.xml
========================================

    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:util="http://www.springframework.org/schema/util"
	xsi:schemaLocation="
    http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
    http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-3.0.xsd">

	<bean id="sampleRelay" class="com.flipkart.aesop.runtime.relay.DefaultRelayFactory">
		<property name="relayConfig" ref="relayConfig" />
		<property name="producerRegistrationList">
			<list>
				<bean
					class="com.flipkart.aesop.runtime.config.InitBackedProducerRegistration">
					<property name="properties">
						<bean id="productRegistrationPropertiesFactory"
							class="org.springframework.beans.factory.config.PropertiesFactoryBean">
							<property name="singleton" value="true" />
							<property name="properties">
								<props>
									<prop
										key="databus.relay.dataSources.sequenceNumbersHandler.file.initVal">4294967300</prop>
								</props>
							</property>
						</bean>
					</property>
					<property name="eventProducer" ref="mysqlPersonProducer"/>
					<property name="physicalSourceConfig" ref="physicalSourceConfig" />
				</bean>
			</list>
		</property>
	</bean>

	<bean id="mysqlPersonProducer" class="com.flipkart.aesop.runtime.producer.MysqlEventProducer">
		<property name="physicalSourceConfig" ref="physicalSourceConfig" />
		<property name="eventsMap" ref="eventsMapRef" />
		<property name="binLogEventMappers" ref="binLogEventMappersRef" />
		<property name="schemaChangeEventProcessor">
			<bean
				class="com.flipkart.aesop.runtime.producer.schema.eventprocessor.impl.NopSchemaChangeEventProcessor" />
		</property>
	</bean>

	<bean id="orToAvroMapper"
		class="com.flipkart.aesop.runtime.producer.mapper.impl.ORToAvroMapper" />

	<util:map id="eventsMapRef" key-type="java.lang.Integer"
		value-type="com.flipkart.aesop.runtime.producer.eventprocessor.BinLogEventProcessor">
		<entry
			key="#{T(com.flipkart.aesop.runtime.producer.constants.MySQLConstants).QUERY_EVENT}"
			value-ref="mutatingQueryEventProcessor" />
		<entry
			key="#{T(com.flipkart.aesop.runtime.producer.constants.MySQLConstants).ROTATE_EVENT}"
			value-ref="rotateEventProcessor" />
		<entry
			key="#{T(com.flipkart.aesop.runtime.producer.constants.MySQLConstants).XID_EVENT}"
			value-ref="commitEventProcessor" />
		<entry
			key="#{T(com.flipkart.aesop.runtime.producer.constants.MySQLConstants).TABLE_MAP_EVENT}"
			value-ref="tableMapEventProcessor" />
		<entry
			key="#{T(com.flipkart.aesop.runtime.producer.constants.MySQLConstants).WRITE_ROWS_EVENT}"
			value-ref="insertEventProcessor" />
		<entry
			key="#{T(com.flipkart.aesop.runtime.producer.constants.MySQLConstants).UPDATE_ROWS_EVENT}"
			value-ref="updateEventProcessor" />
		<entry
			key="#{T(com.flipkart.aesop.runtime.producer.constants.MySQLConstants).DELETE_ROWS_EVENT}"
			value-ref="deleteEventProcessor" />
		<entry
			key="#{T(com.flipkart.aesop.runtime.producer.constants.MySQLConstants).WRITE_ROWS_EVENT_V2}"
			value-ref="insertEventV2Processor" />
		<entry
			key="#{T(com.flipkart.aesop.runtime.producer.constants.MySQLConstants).UPDATE_ROWS_EVENT_V2}"
			value-ref="updateEventV2Processor" />
		<entry
			key="#{T(com.flipkart.aesop.runtime.producer.constants.MySQLConstants).DELETE_ROWS_EVENT_V2}"
			value-ref="deleteEventV2Processor" />
	</util:map>

	<bean id="mutatingQueryEventProcessor"
		class="com.flipkart.aesop.runtime.producer.eventprocessor.impl.MutatingQueryEventProcessor" />
	<bean id="rotateEventProcessor"
		class="com.flipkart.aesop.runtime.producer.eventprocessor.impl.RotateEventProcessor" />
	<bean id="commitEventProcessor"
		class="com.flipkart.aesop.runtime.producer.eventprocessor.impl.CommitEventProcessor" />
	<bean id="tableMapEventProcessor"
		class="com.flipkart.aesop.runtime.producer.eventprocessor.impl.TableMapEventProcessor" />
	<bean id="insertEventProcessor"
		class="com.flipkart.aesop.runtime.producer.eventprocessor.impl.InsertEventProcessor" />
	<bean id="updateEventProcessor"
		class="com.flipkart.aesop.runtime.producer.eventprocessor.impl.UpdateEventProcessor" />
	<bean id="deleteEventProcessor"
		class="com.flipkart.aesop.runtime.producer.eventprocessor.impl.DeleteEventProcessor" />
	<bean id="insertEventV2Processor"
		class="com.flipkart.aesop.runtime.producer.eventprocessor.impl.InsertEventV2Processor" />
	<bean id="updateEventV2Processor"
		class="com.flipkart.aesop.runtime.producer.eventprocessor.impl.UpdateEventV2Processor" />
	<bean id="deleteEventV2Processor"
		class="com.flipkart.aesop.runtime.producer.eventprocessor.impl.DeleteEventV2Processor" />

	<util:map id="binLogEventMappersRef" key-type="java.lang.Integer"
		value-type="com.flipkart.aesop.runtime.producer.mapper.BinLogEventMapper">
		<entry key="40" value-ref="defaultBinLogEventMapper" />
	</util:map>
	<bean id="defaultBinLogEventMapper"
		class="com.flipkart.aesop.runtime.producer.mapper.impl.DefaultBinLogEventMapper">
		<property name="orToAvroMapper" ref="orToAvroMapper" />
	</bean>

	<bean id="physicalSourceConfig" class="com.linkedin.databus2.relay.config.PhysicalSourceConfig">
		<property name="id" value="2000" />
		<property name="name" value="ESBookingsPhysicalSource" />
		<property name="uri"
			value="mysql://or_test%2For_test@localhost:3306/12345/mysql-bin" />
		<property name="sources">
			<list>
				
				 <bean id="logicalSourceConfig"
					class="com.linkedin.databus2.relay.config.LogicalSourceConfig">
					<property name="id" value="2001" />
					<property name="name" value="com.flipkart.aesop.events.es_test.bookings" />
					<property name="uri" value="es_test.bookings" />
					<property name="partitionFunction" value="constant:1" />
				</bean> 
			</list>
		</property>
	</bean>

	<bean id="relayConfig" class="com.flipkart.aesop.runtime.config.RelayConfig">
		<property name="relayProperties">
			<bean id="relayPropertiesFactory"
				class="org.springframework.beans.factory.config.PropertiesFactoryBean">
				<property name="singleton" value="true" />
				<property name="properties">
					<props>
						<prop key="databus.relay.container.httpPort">25021</prop>
						<prop key="databus.relay.container.jmx.rmiEnabled">false</prop>
						<prop key="databus.relay.eventBuffer.allocationPolicy">MMAPPED_MEMORY</prop>
						<prop key="databus.relay.eventBuffer.queuePolicy">OVERWRITE_ON_WRITE</prop>
						<prop key="databus.relay.eventLogReader.enabled">false</prop>
						<prop key="databus.relay.eventLogWriter.enabled">false</prop>
						<prop key="databus.relay.schemaRegistry.type">FILE_SYSTEM</prop>
						<prop key="databus.relay.eventBuffer.maxSize">10240000</prop>
						<prop key="databus.relay.eventBuffer.readBufferSize">10240</prop>
						<prop key="databus.relay.eventBuffer.scnIndexSize">10240000</prop>
						<prop key="databus.relay.eventBuffer.restoreMMappedBuffers">true</prop>
						
					</props>
				</property>
			</bean>
		</property>
		<property name="schemaRegistryLocation" value="schemas_registry" />
		<property name="mmappedDirectoryLocation" value="/tmp/sandbox/mmapped_directory" /> 
		<property name="maxScnDirectoryLocation" value="/tmp/sandbox/maxscn_directory" /> 
	</bean>

    </beans>

**Comment by karims** [comment]
spring-client-config.xml
=======================

    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:util="http://www.springframework.org/schema/util"
	xsi:schemaLocation="
    http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
    http://www.springframework.org/schema/util
	http://www.springframework.org/schema/util/spring-util-2.5.xsd">

	<bean
		class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="location" value="classpath:project.properties" />
	</bean>

	<bean id="defaultEventConsumerFactory"
		class="com.flipkart.aesop.eventconsumer.implementation.DefaultEventConsumerFactoryBean">
		<property name="mapper" ref="defaultMapperImpl" />
		<property name="destinationProcessorMap">
			<map>
				<entry key-ref="upsertDbusOpCode" value-ref="elasticSearchUpsertProcessor" />
				<entry key-ref="deleteDbusOpCode" value-ref="elasticSearchDeleteProcessor" />
			</map>
		</property>
		<property name="sourceEventFactory" ref="sourceEventFactory" />
		<property name="destinationGroupSet">
			<list>
				<value>1</value>
			</list>
		</property>
		<property name="totalDestinationGroups" value="1" />
	</bean>

	<bean id="defaultMapperImpl"
		class="com.flipkart.aesop.mapper.implementation.DefaultMapperImpl">
		<property name="configFilePath" value="resources/application.conf" />
		<property name="configRoot" value="MAPPER_CONFIG" />
		<property name="mapperConfig" ref="mapperConfig" />
		<property name="mapperTypeList">
			<list>
				<ref bean="noNamespaceEntityMapperType" />
				<ref bean="noEntityMapperType" />
				<ref bean="namespaceEntityMapperType" />
			</list>
		</property>
		<property name="eventGroupFinder" ref="defaultEventGroupFinder" />
		<property name="destinationEventFactory" ref="destinationEventFactory" />
	</bean>

	<util:constant id="upsertDbusOpCode"
		static-field="com.linkedin.databus.core.DbusOpcode.UPSERT" />
	<util:constant id="deleteDbusOpCode"
		static-field="com.linkedin.databus.core.DbusOpcode.DELETE" />

	<bean id="mapperConfig"
		class="com.flipkart.aesop.mapper.config.implementation.MapperConfigImpl"
		factory-method="getInstance" />

	<util:constant id="noNamespaceEntityMapperType"
		static-field="com.flipkart.aesop.mapper.implementation.MapperType.MAP_WITHOUT_SOURCE_NAMESPACE_ENTITY_CONFIG" />
	<util:constant id="noEntityMapperType"
		static-field="com.flipkart.aesop.mapper.implementation.MapperType.MAP_WITHOUT_SOURCE_ENTITY_CONFIG" />
	<util:constant id="namespaceEntityMapperType"
		static-field="com.flipkart.aesop.mapper.implementation.MapperType.MAP_WITH_SOURCE_ENTITY_CONFIG" />

	<bean id="defaultEventGroupFinder"
		class="com.flipkart.aesop.mapper.eventGroupFilter.implementation.DefaultEventGroupFinderImpl"
		factory-method="getInstance" />

	<bean id="destinationEventFactory"
		class="com.flipkart.aesop.event.implementation.DestinationEventFactory" />

	<bean id="sourceEventFactory"
		class="com.flipkart.aesop.event.implementation.SourceEventFactory" />

	<bean id="elasticSearchUpsertProcessor"
		class="com.flipkart.aesop.processor.es.upsert.ElasticSearchUpsertProcessor">
        <property name="elasticSearchClient" ref="elasticSearchClient"/>
	</bean>

	<bean id="elasticSearchDeleteProcessor"
		class="com.flipkart.aesop.processor.es.delete.ElasticSearchDeleteProcessor">
        <property name="elasticSearchClient" ref="elasticSearchClient"/>
	</bean>

    <bean id="elasticSearchClient" class="com.flipkart.aesop.processor.es.client.ElasticSearchTransportClient">
        <property name="elasticSearchConfig" ref="elasticSearchConfig"/>
    </bean>

    <bean id="elasticSearchConfig" class="com.flipkart.aesop.processor.es.config.ElasticSearchConfig">
        <constructor-arg value="config.infra.es.conf" />
    </bean>

    <bean id="sampleClient"
          class="com.flipkart.aesop.runtime.clusterclient.DefaultClusterClientFactory">
        <property name="clientClusterConfig" ref="clientClusterConfig" />
        <property name="clusterRegistrations">
            <list>
                <bean class="com.flipkart.aesop.runtime.config.ClusterRegistration">
                    <property name="clusterName" value="pz_elastic_search_cluster" />
                    <property name="consumerFactory">
                        <bean class="com.flipkart.aesop.eventconsumer.ConsumerFactory">
                            <property name="eventConsumerFactoryList">
                                <list>
                                    <ref bean="defaultEventConsumerFactory" />
                                </list>
                            </property>
                            <property name="totalDestinationGroups" value="1" />
                        </bean>
                    </property>
                    <property name="logicalSources">
                        <list value-type="java.lang.String">
                            <value>com.flipkart.aesop.events.es_test.bookings</value>
                        </list>
                    </property>
                </bean>
            </list>
        </property>
    </bean>

    <bean id="clientClusterConfig" class="com.flipkart.aesop.runtime.config.ClientClusterConfig">
        <property name="clientProperties">
            <bean id="clientPropertiesFactory"
                  class="org.springframework.beans.factory.config.PropertiesFactoryBean">
                <property name="singleton" value="true" />
                <property name="properties">
                    <props>
                        <prop key="databus.client.container.httpPort">11125</prop>
                        <prop key="databus.client.container.jmx.rmiEnabled">false</prop>
                        <prop key="databus.client.connectionDefaults.pullerRetries.initSleep">1</prop>
                        <prop key="databus.client.connectionDefaults.pullerRetries.maxRetryNum">-1</prop>
                        <prop key="databus.client.checkpointPersistence.clearBeforeUse">false</prop>
                        <prop key="databus.client.connectionDefaults.enablePullerMessageQueueLogging">false</prop>
                    </props>
                </property>
            </bean>
        </property>
        <property name="relayClientConfigs">
            <list>
                <bean class="com.flipkart.aesop.runtime.config.RelayClientConfig">
                    <property name="relayId" value="2001" />
                    <property name="relayHost" value="localhost" />
                    <property name="relayPort" value="25021" />
                    <property name="relayLogicalSourceNames">
                        <list value-type="java.lang.String">
                            <value>com.flipkart.aesop.events.es_test.bookings</value>
                        </list>
                    </property>
                </bean>
            </list>
        </property>
        <property name="clusterInfoConfigs">
            <list>
                <bean class="com.flipkart.aesop.runtime.config.ClusterInfoConfig">
                    <property name="id" value="1" />
                    <property name="clusterName" value="pz_elastic_search_cluster" />
                    <property name="zkAddr" value="localhost:2181" />
                    <property name="numPartitions" value="2" />
                    <property name="quorum" value="1" />
                    <property name="zkSessionTimeoutMs" value="3000" />
                    <property name="zkConnectionTimeoutMs" value="3000" />
                    <property name="checkpointIntervalMs" value="300000" />
                </bean>
            </list>
        </property>

        <property name="checkpointDirectoryLocation" value="../../data-dir/client_checkpoint_directory" />
    </bean>
    </beans>

**Comment by karims** [comment]
posting error once again:

    16:21:31.737 [pz_elastic_search_cluster-1-RelayDispatcher] WARN  c.l.databus.client.GenericDispatcher.doDispatchEvents 786 es_test_bookings_pz_elastic_search_cluster-1 - EOP with scn=0
    16:21:31.737 [callback-1] INFO  c.l.d.c.consumer.LoggingConsumer.doStartDataEventSequence 344 c.l.d.c.consumer.LoggingConsumer - startDataEventSequence:{"sourceId":2000,"sequence":4294992653}
    16:21:31.737 [pz_elastic_search_cluster-1-RelayDispatcher] ERROR c.l.databus.client.GenericDispatcher.doCheckStartSource 527 es_test_bookings_pz_elastic_search_cluster-1 - Unable to find schema: srcid=2001 name=com.flipkart.aesop.events.es_test.bookings schemaId=055f1eedd345aa57fd55e44583260210
    16:21:31.737 [pz_elastic_search_cluster-1-RelayDispatcher] INFO  c.l.databus.client.GenericDispatcher.doRollback 279 es_test_bookings_pz_elastic_search_cluster-1 - Rolling back the dispatcher to last successful checkpoint. Number of remaining retries for dispatcher to replay events = 2147483647
    16:21:31.738 [pz_elastic_search_cluster-1-RelayDispatcher] INFO  c.l.databus2.core.BackoffTimer.sleep 108 c.l.d.c.BackoffTimerStaticConfigBuilder - pz_elastic_search_cluster-1-RelayDispatcher.errorRetries: error sleep, ms: 27184
    16:21:31.762 [pz_elastic_search_cluster-0-RelayDispatcher] INFO  c.l.databus.client.GenericDispatcher.doRollback 298 es_test_bookings_pz_elastic_search_cluster-0 - Rolling back to SCN : {"sourceId":2000,"sequence":4295011146}
    16:21:31.763 [pz_elastic_search_cluster-0-RelayDispatcher] INFO  c.l.databus.client.GenericDispatcher.doRollback 321 es_test_bookings_pz_elastic_search_cluster-0 - Rolled back to last successful checkpoint position in the buffer: DbusEventIterator: {identifier: pz_elastic_search_cluster-0-RelayDispatcher.iter.save-387146881, currentPosition: 175:[GenId=0;Index=0(lim=8388608,cap=8388608);Offset=175], iteratorTail: 8529:[GenId=0;Index=0(lim=8388608,cap=8388608);Offset=8529], lockToken={ownerName:pz_elastic_search_cluster-0-RelayDispatcher.iter.save-387146881, range:Range [start=175, end=8529], created:1439376420038, lastUpdated:1439376420038}}
    16:21:31.763 [callback-1] INFO  c.l.d.c.consumer.LoggingConsumer.doStartDataEventSequence 344 c.l.d.c.consumer.LoggingConsumer - startDataEventSequence:{"sourceId":2000,"sequence":4295012148}
    16:21:31.763 [pz_elastic_search_cluster-0-RelayDispatcher] ERROR c.l.databus.client.GenericDispatcher.doCheckStartSource 527 es_test_bookings_pz_elastic_search_cluster-0 - Unable to find schema: srcid=2001 name=com.flipkart.aesop.events.es_test.bookings schemaId=055f1eedd345aa57fd55e44583260210

**Comment by karims** [comment]
On the mysql relay side, i get this exception:


    16:42:44.715 [worker1580183171-18] INFO  c.l.d.c.d.DatabusSubscription.loadAndRegisterCodecs 555 c.l.d.c.d.DatabusSubscription - Registering URI codecs.
    16:42:44.729 [worker1580183171-18] ERROR c.l.d.c.m.m.AbstractMonitoringMBean.registerAsMbean 190 c.l.d.c.m.m.AbstractMonitoringMBean - Unable to register to mbean server
    javax.management.InstanceAlreadyExistsException:     com.linkedin.databus2:ownerId=1580183171,dimension=ESBookingsPhysicalSource_2000.outbound.source.2001,type=AggregatedDbusEventsTotalStats
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) ~[na:1.8.0_51]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898) ~[na:1.8.0_51]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966) ~[na:1.8.0_51]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) ~[na:1.8.0_51]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) ~[na:1.8.0_51]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[na:1.8.0_51]
	at com.linkedin.databus.core.monitoring.mbean.AbstractMonitoringMBean.registerAsMbean(AbstractMonitoringMBean.java:181) ~[databus-core-impl-2.0.0.fk.001.jar:na]

**Comment by pratyay-banerjee** [comment]
From the diff, I can only see the logicalSourceConfig "id" in relay-config  and the relayId  in client-config as same, can you change those to different values.
And do a clean start, by removing the sandbox folder, doing a "reset master" in mysql and removing the pz_elastic_search_cluster from zookeeper.

**Comment by karims** [comment]
Thanks. The problem was this: dimension=ESBookingsPhysicalSource

I changes that ID to ES2BookingsPhysicalSource. It worked fine.

One more question, how do I get historical MySQL data as well into ES? Is there a way with Aesop? [I can start a new question if you want.]

**Comment by pratyay-banerjee** [comment]
Without Binlogs from start there is no way to relay historical data from MySql to ES. You can solve this by starting a slave with Blackhole engine, and loading data using a mysqldump, not an lvm snapshot. This way only binlogs will be generated for the blackhole engine table, which you can relay through ES.

**Comment by karims** [comment]
Thanks so much :)

**Comment by pratyay-banerjee** [comment]
No Problem. Closing issue.
