### ISSUE TITLE
mysql connection uri

### ISSUE THREAD

**Issue by karims** [Flipkart/aesop#37]
I have a very silly question. The connection to mysql is done using an url in the spring-relay-config.xml. The uri is `mysql://or_test%2For_test@localhost:3306/12345/mysql-bin`.

Ofcourse this works, but I am confused where this `12345` comes from in the uri?

**Comment by regunathb** [comment]
From what I see in the source here : https://github.com/Flipkart/aesop/blob/master/producers/mysql-producer/src/main/java/com/flipkart/aesop/runtime/producer/MysqlEventProducer.java, the 12345 is used as the OpenReplicator server identifier.
