### ISSUE TITLE
how to recreate the original database

### ISSUE THREAD

**Issue by wanghaisheng** [Flipkart/aesop#43]
if i deploy a relay to mysql,and successfully get the cdc event message in kafka topics,how to recreate the original mysql database from these messages ,is there a complete example to follow?
thx

**Comment by aryaKetan** [comment]
@wanghaisheng: you can only re-create a database if your bin log entries has all the entries that ever got created since creation of the database. If that's not the case, then re-creating a database from bin logs is not possible. you need to first scan the table and come to the latest available bin log position. post that you can use either a blocking bootstrap or the normal relay-consumer aesop topology for moving data from 1 database to another. Just curious to know why mysql replication does not suffice?

**Comment by wanghaisheng** [comment]
@aryaKetan right now  our  mysql does not enable bin log feature.if i want to use aesop to get all the change data nearly real time, i need to enable bin log first.use a blocking bootstrap to restore the existing data and use normal relay-consumer method to get the following change data.
this is my purpose though

**Comment by dhirendrafkl** [comment]
@wanghaisheng We had a similar scenario, where we wanted to push our MySql data to Hbase. We took a db dump recreated the a new db with this dump while bin log logging was enabled, and made this new db a slave to original db. Started boot strap aesop on using this newly created db. Once cathup was done we started aesop relay, and consumer on existing db.

**Comment by wanghaisheng** [comment]
@dhirendrafkl   
1 you mean after enable bin log feature ,you took a  db dump and manually import into new db
2 what do you mean by  made new db as a slave ?in our situation  original db is using cloud service ,and new one is located in our self built data center 
3 " Started boot strap aesop on using this newly created db" do you mean the started bootstrap aesop against new mysql db  exist with the original mysql db ,in our situation  we need two mysql instance on our cloud service ,original one enable bin log and new one not ,but take new one as a slave of the original one ,started bootstrap   process and once catchup was done  we abandon this new mysql and run aesop relay against the original one ,and  consumer on the machine  in my data center and the target mysql database

**Comment by dhirendrafkl** [comment]
@wanghaisheng 
To Summarize:

1. Enabled bin log on original db.
2. Take a dump from original db.
3. Create a new db with bin log enabled.
4. Import the dump to this newly created db.
5. Make this newly created db a slave to original db.
6. Start bootstrap on newly created db, and wait for catch up.
7. After catchup stop boot strap.
8. Start relayer consumer on original db to start from catch location.

I guess same can be applied to your situation too.

**Comment by wanghaisheng** [comment]
@dhirendrafkl  definitely  what i  want  thx  let me try

**Comment by wanghaisheng** [comment]
@dhirendrafkl   there is still 2  questions
1  step 6  ,i can use sample-mysql-mysql-blocking-bootstrap to realize the catchup, i find out bootstrap don`t serialize change event to avro record,because original db(our transaction db) is always changing, how to determine when is catchup
2. step 8 i can use exsting sample-mysql-relay to detect change event on original db, i need to customize  sample-client-cluster sample/sample-elastic-search-client-cluster-consumer to consume avro serialized change event and save it into my target mysql db(i can refer the config in sample-mysql-mysql-blocking-bootstrap) ,am I right?
