### ISSUE TITLE
configuration in chained kafka-client-cluster-consumer to mysql-client-cluster-consumer

### ISSUE THREAD

**Issue by wanghaisheng** [Flipkart/aesop#49]
what i want is to use kafka as the unique pipeline to consumer all the change data from relay server ,bootstrap or not ,if  there is a need to rebuild the original database,then we can use mysql-client-cluster-consumer to do this job.

**Comment by regunathb** [comment]
I am sorry but I am unable to understand your question. Can you elaborate please?

**Comment by wanghaisheng** [comment]
right now  i deploy a sample-mysql-mysql-blocking-bootstrap (against a slave of my source mysql)which can get all my source mysql database to my target temp mysql ,then came a usual relay model to do the live update thing ,here i can use a kafka consumer or simple mysql consumer(based on data layer mysql to do the avro to sql mapping ,then insert data into target database or just use the mysql consumer part in sample-mysql-mysql-blocking-bootstrap project)  or  I can cut the relay model .only use sample-mysql-mysql-blocking-bootstrap  to do get data sync between source and target.
what i want to do is always use the kafka consumer ,relay server is simple and straight,but how to deal with the old data,sample-mysql-mysql-blocking-bootstrap  don`t producer avro record .
how to combine  aesop component to accomplish my purpose

**Comment by regunathb** [comment]
Closing this as it appears to be a question around usage and not an issue.
