### ISSUE TITLE
differences and use cases between bootstrap and blocking bootstrap

### ISSUE THREAD

**Issue by wanghaisheng** [Flipkart/aesop#50]
under the runtimes directory,there is  
-runtime-blocking-bootstrap(based on databus-bootstrap-server)
-runtime-bootstrap(based on databus-bootstrap-server)
-runtime-client-bootstrap-producer
and the sample directory contains
-sample-bootstrap-server
-sample-client-bootstrap-producer
-sample-mysql-mysql-blocking-bootstrap

the only difference between these following two is serialization of change event 
-runtime-blocking-bootstrap(based on databus-bootstrap-server)
-runtime-bootstrap(based on databus-bootstrap-server)

```
When the system is being set up for the first time there will be a lot of data that has been accumulated since day one. This data needs to be transformed and stored in destination data store the way it would be done for events in real time.

However there is an issue in reusing the usual relay and client. Since the throughput of the client would be dependant on that of the destination data store, the clients would fall off the Relay. The buffer in the Relay does not help as the Relay throughput is far higher than that of Client and hence the buffer fills up and starts overwriting even before the client has been able to pull that event. 
```
as the proposal in issue https://github.com/Flipkart/aesop/issues/43
```
1.Enabled bin log on original db.
2.Take a dump from original db.
3.Create a new db with bin log enabled.
4.Import the dump to this newly created db.
5.Make this newly created db a slave to original db.
6.Start bootstrap on newly created db, and wait for catch up.
7.After catchup stop boot strap.
8.Start relayer consumer on original db to start from catch location.

```
we use 
-sample-mysql-mysql-blocking-bootstrap
to realize the first 7 steps and we use for the last two steps
-sample-mysql-relay
-sample-kafka-client-cluster-consumer

the question is  when and how to use 
```
-sample-bootstrap-server
-sample-client-bootstrap-producer
```
.how do relay know the buffer is full or the incoming event will overwrite and push these ones to a bootstrap server,how do client know fall off the relay and start  client-bootstrap-producer to get  long look-back updates from the bootstrap server.

right now our mysql does not enable bin log feature.if i want to use aesop to get all the change data nearly real time, i need to enable bin log first.
i can use a blocking bootstrap to restore the existing data and use normal relay-consumer method to get the following change data.

@aryaKetan @dhirendrafkl @regunathb

**Comment by regunathb** [comment]
Yes, you need to enable the MySQL bin log and do remember to set it up for ROW replication.
And yes, you can use the Blocking bootstrap to "seed" the system with existing/old data and then use the Aesop Relay for live updates.

**Comment by wanghaisheng** [comment]
@regunathb when i  use Aesop Relay for live updates,what if the source database througput is too large and consumer could not deal with the data in buffer ,what i want to know  is  do i need and how to set up a regular bootstrap with a Relay ?if these special situation comes, relay can move the data in the buffer to bootstrap and tell consumer go to fetch these data in bootstrap server ,then comes to the data in buffer?
in your use case ,Blocking bootstrap  or regular bootstrap  you use to "seed" the system with existing/old data

**Comment by regunathb** [comment]
We use the blocking bootstrap when we have to move large amounts of data and when the producer throughput is much higher than what the consumer can process - this is typically a use case like data migration/one time setup.
The bootstrap exists to support consumers of varying speeds where a slower consumer that falls off the relay can catchup from the bootstrap and then move to online consumption. This switch is automatic if you configure bootstrap config for any consumer.

**Comment by wanghaisheng** [comment]
i look for this bootstap config in all sample-client projects only this one
```
<!-- 	
		<property name="bootstrapClientConfigs">
			<list>
				<bean class="com.flipkart.aesop.runtime.config.BootstrapClientConfig">
					<property name="bootstrapId" value="101" />
					<property name="bootstrapHost" value="localhost" />
					<property name="bootstrapPort" value="11145" />
					<property name="bootstrapLogicalSourceNames">
						<list value-type="java.lang.String">
							<value>com.flipkart.aesop.events.sample.person.Person</value>
						</list>
					</property>
				</bean>
			</list>
		</property>
 -->		
```
then for a client,we can have two choices,a regular bootstrap server and a blocking bootstrap server
for example if i can successfully run "sample-mysql-relay" "sample-bootstrap-server" "sample-mysql-mysql-blocking-bootstrap" i got a relay server,bootstrap server and a blocking one.
then  i want to use  "sample-console-appender-client-cluster-consumer", how to config these two options in  spring-client-config.xml ?

**Comment by regunathb** [comment]
Closing this as it appears to be a question around usage and not an issue.
