### ISSUE TITLE
how  to express index in one table

### ISSUE THREAD

**Issue by wanghaisheng** [Flipkart/aesop#51]
if we have a table like this
CREATE TABLE IF NOT EXISTS `person` (
  `ID` varchar(36) NOT NULL ,
  `Code` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `index_name` (`Code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

we can define a application.conf in blocking bootstrap server
```
MYSQL_CONFIG
{
	or_test:
	{
		"Person"=[
		{
			"destinationNamespace":"or_test",
			"destinationEntity":"PERSONPARALLEL",
			"columnMap": {
				"ID":"ID",
				"Code":"Code"
			},
			"primaryKeyList": [ "pid" ]
		}
		]
	}
 }

```
how to express the "  KEY `index_name` (`Code`)" part in table definition

**Comment by aryaKetan** [comment]
the hocon config used by clients ( as in the e.g. above)  do not take into account any KEY.
the primaryKeyList is configurable by clients and independent of the table definition. You can give any set of column names as primaryKeyList as per your need.
