### ISSUE TITLE
how to set the max

### ISSUE THREAD

**Issue by wanghaisheng** [Flipkart/aesop#59]
there is a debug info when i run mysql-blocking-bootstrap server, how to configure this resource poll max number?
```
10:14:33.918 [pool-8-thread-1] DEBUG c.m.v.resourcepool.BasicResourcePool.prelimCheckoutResource 554 c.m.v.resourcepool.BasicResourcePool - acquire test -- pool is already maxed out. [managed: 15; max: 15]

```

**Comment by regunathb** [comment]
The question is a bit vague. Can you be more precise and provide details please.
It might also be a better option to use the mailing lists to ask questions and limit github issues to real issues.
